<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TransferImageQR</RootNamespace>
    <AssemblyName>TransferImageQR</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransferImageQR.Application\TransferImageQR.Application.csproj" />
    <ProjectReference Include="..\TransferImageQR.Infrastructure\TransferImageQR.Infrastructure.csproj" />
  </ItemGroup>

</Project>
