<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TransferImageQR</RootNamespace>
    <AssemblyName>TransferImageQR</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransferImageQR.Application\TransferImageQR.Application.csproj" />
    <ProjectReference Include="..\TransferImageQR.Infrastructure\TransferImageQR.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\NotoSansJP-Variable.ttf"
                      LogicalName="TransferImageQR.Assets.Fonts.NotoSansJP.ttf" />
    <None Update="Assets\Fonts\OFL.txt"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest"
          TargetPath="NotoSansJP-OFL.txt" />
  </ItemGroup>

</Project>
